/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import javax.swing.JOptionPane;

/**
 *
 * @author marcos
 */
public class CalculadoraIMC extends javax.swing.JFrame {

    /**
     * Creates new form CalcIMC
     */
    public CalculadoraIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        abaIMC = new javax.swing.JPanel();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        txtIMC = new javax.swing.JTextField();
        lblIMC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora IMC");
        setResizable(false);

        lblAltura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAltura.setText("Altura: ");

        lblPeso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPeso.setText("Peso:");

        btnCalc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        txtIMC.setEditable(false);
        txtIMC.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIMC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblIMC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIMC.setText("Seu IMC:");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Ex: 1.80");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ex: 70.5");

        javax.swing.GroupLayout abaIMCLayout = new javax.swing.GroupLayout(abaIMC);
        abaIMC.setLayout(abaIMCLayout);
        abaIMCLayout.setHorizontalGroup(
            abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaIMCLayout.createSequentialGroup()
                .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaIMCLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeso)
                            .addComponent(lblAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addComponent(lblIMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaIMCLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnCalc)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        abaIMCLayout.setVerticalGroup(
            abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaIMCLayout.createSequentialGroup()
                .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaIMCLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeso)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaIMCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(abaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIMC)
                            .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addComponent(btnCalc)
                .addGap(96, 96, 96))
        );

        abas.addTab("IMC", abaIMC);

        tblInfo.setBackground(new java.awt.Color(204, 204, 204));
        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MENOR QUE 18.5", "MAGREZA", "                        0"},
                {"ENTRE 18.5 E 24.9", "NORMAL", "                        0"},
                {"ENTRE 25.0 E 29.9", "SOBREPESO", "                        1"},
                {"ENTRE 30.0 E 39.9", "OBESIDADE", "                        2"},
                {"MAIOR QUE 40.0", "OBESIDADE GRAVE", "                        3"}
            },
            new String [] {
                "IMC", "CLASSIFICAÇÃO", "OBESIDADE - GRAU"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfo.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tblInfo.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tblInfo);
        if (tblInfo.getColumnModel().getColumnCount() > 0) {
            tblInfo.getColumnModel().getColumn(0).setResizable(false);
            tblInfo.getColumnModel().getColumn(1).setResizable(false);
            tblInfo.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout abaInfoLayout = new javax.swing.GroupLayout(abaInfo);
        abaInfo.setLayout(abaInfoLayout);
        abaInfoLayout.setHorizontalGroup(
            abaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        abaInfoLayout.setVerticalGroup(
            abaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaInfoLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        abas.addTab("Info", abaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionaColuna(double imc){
        if(imc <= 18.5){
            tblInfo.setRowSelectionInterval(0, 0);
        } else if(imc > 18.5 && imc <= 24.9){
            tblInfo.setRowSelectionInterval(1, 1);
        } else if(imc >= 25.0 && imc <= 29.9){
            tblInfo.setRowSelectionInterval(2, 2);
        } else if(imc >= 30.0 && imc <= 39.9){
            tblInfo.setRowSelectionInterval(3, 3);
        } else {
            tblInfo.setRowSelectionInterval(4, 4);
        }
    }
    
    
    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        try {
           if(txtAltura.getText().contains(",") || txtPeso.getText().contains(",")){
               JOptionPane.showMessageDialog(null, "Troque a (vírgula) por um (ponto)!");
            } else {
               double altura = Double.parseDouble(txtAltura.getText());
               double peso = Double.parseDouble(txtPeso.getText());
               
               if(altura > 0 && peso > 0){
                   double imc = peso / Math.pow(altura, 2);
                   
                   selecionaColuna(imc);
                   
                   Double.toString(imc);
                   txtIMC.setText(String.format("%.2f", imc));
               } else {
                   JOptionPane.showMessageDialog(null, "Valor inválido!");
               }
           }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campo vazio! \nInsira um valor!");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculadoraIMC form = new CalculadoraIMC();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaIMC;
    private javax.swing.JPanel abaInfo;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
